name: Auto Add Retrospectives to Project

on:
  issues:
    types: [opened, labeled]

jobs:
  add-to-project:
    name: Add issue to studio project
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'retrospective')
    steps:
      - name: Add To GitHub projects
        uses: actions/add-to-project@v2.0.0
        with:
          project-url: https://github.com/orgs/Cosmic-Couch-Studios/projects/6
          github-token: ${{ secrets.GITHUB_TOKEN }}
